---
- name: my test playbook
  hosts: webservers
  become: yes
  tasks:
  - name: install httpd pkg
    yum:
      name: httpd
      state: installed


  - name: start httpd service
    service:
      name: httpd
      state: started
