---
- name: my test playbook
  hosts: all
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"


  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"


  - name: install apache2 pkg
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 serv
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"


  - name: copy index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html

