---
- name: my test playbook
  hosts: all
  become: true
  tasks:
  - name: install httpd pkg
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd ser
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: Install apache2 pkg
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 ser
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
