---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"


  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat pkg
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
      dest: /opt

  - name: untar apache pkg
    unarchive:
      src: /opt/apache-tomcat-8.5.78.tar.gz
      dest: /opt
      remote_src: yes  # check the pkg in remote machine

  - name: add execution permissions on startup.sh file
    file:
      path: /opt/apache-tomcat-8.5.78/bin/startup.sh
      mode: 0777
  - name: start tomcat service
    shell: nohup ./startup.sh       # nohup --> to run contiuesly
    args:
      chdir: /opt/apache-tomcat-8.5.78/bin
